# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 12, 8, 25, 25, 857329, tzinfo=utc), null=True),
        ),
    ]
